services:

  openswoole:
    image: openswoole/swoole:latest
    container_name: openswoole
    ports:
      - "9501:9501"
    volumes:
      - ./openswoole:/var/www
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=openswoole
      - GF_SECURITY_ADMIN_PASSWORD=openswoole
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cat
      POSTGRES_USER: cat
      POSTGRES_PASSWORD: cat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  prom_data:
  postgres_data:
